### PR TITLE
Configure Apache for Open Vault.

### PR DESCRIPTION
**Pull request by afred**
@mccalluc?

### CODE REVIEW

**Comment by mccalluc** [comment]
@afred: what's the j2 about?

**Comment by afred** [comment]
@mccalluc jinja2 template. It's like .erb for python.

**Comment by mccalluc** [comment]
@afred: Cool. Do we anticipate using the templating? Or will it be more surprising/annoying in the long wrong if we can't template? If it's not something we use, I worry a tiny bit about someone making an edit and not realizing they've used a template meta-character.

(I'll take a moment and see if I can get this to run for me.)

**Comment by afred** [comment]
@mccalluc good point. This is my first try at using a template, and a all the examples I've seen use '.j2' extension. I didn't try without it.

**Comment by afred** [comment]
@mccalluc see latest commit in this PR.

**Comment by mccalluc** [comment]
(Didn't get around to running this: Should do it first thing tomorrow.)

**Comment by mccalluc** [comment]
@afred: arg: something weird on my side:

```
$ pip install ansible
Requirement already satisfied (use --upgrade to upgrade): ansible in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /Library/Python/2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Library/Python/2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /Library/Python/2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /Library/Python/2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /Library/Python/2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Library/Python/2.7/site-packages (from jinja2->ansible)
```

but

```
[mla-playbooks]$ ansible-playbook -i openvault/hosts openvault/site.yml --private-key ~/.ssh/ansible-test.pem
-bash: ansible-playbook: command not found
```

**Comment by mccalluc** [comment]
@afred: still not finding the ansible-playbook. Could you do a `which`? Going to uninstall/reinstall and see if that helps.

```
[mla-playbooks]$ pip show ansible | grep Location
Location: /Library/Python/2.7/site-packages
[mla-playbooks]$ find /Library/Python/2.7/site-packages/ansible | grep playbook
/Library/Python/2.7/site-packages/ansible/playbook
/Library/Python/2.7/site-packages/ansible/playbook/__init__.py
/Library/Python/2.7/site-packages/ansible/playbook/__init__.pyc
/Library/Python/2.7/site-packages/ansible/playbook/play.py
/Library/Python/2.7/site-packages/ansible/playbook/play.pyc
/Library/Python/2.7/site-packages/ansible/playbook/task.py
/Library/Python/2.7/site-packages/ansible/playbook/task.pyc
```

About the conflict: Maybe make a new branch from your fafc3f5, and just abandon my README tweaks, since your other PR has that covered?

**Comment by afred** [comment]
@mccalluc whoops.. sorry. Gotta be more careful on the `git push -f`

**Comment by afred** [comment]
```
;^) which ansible-playbook
/usr/local/bin/ansible-playbook
```

I installed ansible with `pip`.

```
;^) pip show ansible
---
Metadata-Version: 1.0
Name: ansible
Version: 1.9.4
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: michael@ansible.com
License: GPLv3
Location: /Library/Python/2.7/site-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto
/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

And I installed `pip` with `easy_install` (i think)..

I'm not sure how installed Python.

**Comment by mccalluc** [comment]
Ok, running now. I get the apache test page. I'll merge this, and then go ahead and try the capistrano PR.

**Pull request merged**
