### PR TITLE
Adds tasks to install Passenger w/ Apache 2

### PR DESCRIPTION
**Pull request by afred**

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc please review. Email forthcoming with more info.. stand by.

**Comment by mccalluc** [comment]
@afred: First time I've tried, but I get this message:

```
[mla-playbooks]$ git checkout 50-add-tasks-for-installing-passenger
Branch 50-add-tasks-for-installing-passenger set up to track remote branch 50-add-tasks-for-installing-passenger from origin.
Switched to a new branch '50-add-tasks-for-installing-passenger'
[mla-playbooks]$ ansible-playbook -i openvault/hosts openvault/site.yml --private-key ~/.ssh/ansible-test.pem
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure 
become_method is 'sudo' (default). This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to have been in '/Users/chuck_mccallum/starting/mla-playbooks/roles/crushlovely.capistrano/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
galaxy_info:
^ here
```

**Comment by mccalluc** [comment]
@afred: maybe you're on a different version of ansible than I am? https://github.com/ansible/ansible/issues/13496

```
[mla-playbooks]$ ansible --version
ansible 2.0.0.2
  config file = /Users/chuck_mccallum/starting/mla-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by mccalluc** [comment]
@afred: merged.

```
sudo pip install ansible==1.9.4
ansible-playbook -i openvault/hosts openvault/site.yml --private-key ~/.ssh/ansible-test.pem
...
PLAY RECAP ******************************************************************** 
54.209.250.227             : ok=35   changed=22   unreachable=0    failed=0 
```

**Pull request merged**
